######################################################################
# Automatically generated by qmake (3.0) Sun Aug 30 11:26:31 2015
######################################################################

TEMPLATE = app
TARGET = x-maxine-client
INCLUDEPATH += .
QT += core dbus

QMAKE_CXXFLAGS = -std=c++11

# Input
SOURCES += main.cpp
